apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017  # Choose a port in the 30000–32767 range
