apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
type: Opaque
data:
  username: YWRtaW51c2Vy  # base64 for 'adminuser'
  password: cGFzc3dvcmQxMjM=  # base64 for 'password123'
  authSource: YWRtaW4= # base64 for 'admin'