apiVersion: v1
kind: Secret
metadata:
  name: db-connection
type: Opaque
data:
  db: 'bXlkYg=='
  dbCollection: 'dXNlcnM='
  seedMongoUri: 'bW9uZ29kYjovL21vbmdvLTAubW9uZ28taGVhZGxlc3MuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbC8/YXV0aFNvdXJjZT1hZG1pbg=='
  # base 64 for 'mongodb://mongo-0.mongo-headless.default.svc.cluster.local/?authSource=admin'
